##
# CA build script
##

Import('env')

print "Reading common folder script"

ca_os = env.get('TARGET_OS')
src_dir = env.get('SRC_DIR')
root_dir = Dir('#').abspath
cur_dir = Dir('.').abspath

print "COMMON DIR: ", cur_dir

ca_common_path = src_dir   # root_dir + 'common/'
ca_common_src_path = cur_dir + "/"  # ca_common_path + 'src/'

env.AppendUnique(CPPPATH = [
	cur_dir + '/include/',
	src_dir + '/logger/include/',
	])

######################################################################
# Source files and Target(s)
######################################################################
ca_common_src = [
		ca_common_src_path + 'uarraylist.c',
		ca_common_src_path + 'ulinklist.c',
		ca_common_src_path + 'uqueue.c',
		ca_common_src_path + 'caremotehandler.c'
	]

if env['POSIX_SUPPORTED']:
	platform_src = [
		ca_common_src_path + 'cathreadpool_pthreads.c',
		ca_common_src_path + 'camutex_pthreads.c'
	]
else:
	platform_src = [
		ca_common_src_path + 'camutex_noop.c'
		]


env.AppendUnique(CA_SRC = ca_common_src)
env.AppendUnique(CA_SRC = platform_src)
